name: maven demo
on:
  push:
    branches: [main]

jobs:
  task-formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - run: mvn compile exec:java
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorld-jar
          path: build/*.jar
          if-no-files-found: error
