name: Release GA

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64

    - name: Set branch-specific tag
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        echo "TAG_NAME=latest/${BRANCH_NAME}" >> ${GITHUB_ENV}
        echo "RELEASE_NAME=Latest Release (${BRANCH_NAME})" >> ${GITHUB_ENV}

    - name: Delete existing tag and release
      run: |
        gh release delete ${{ env.TAG_NAME }} --yes || true
        git push origin :refs/tags/${{ env.TAG_NAME }} || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn package

    - name: Create branch-specific latest tag
      run: |
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_NAME }}
        files: target/*.jar
        generate_release_notes: true
